"use strict";
exports.__esModule = true;
var common_1 = require("./common");
var selectionSortFunc_1 = require("./selectionSortFunc");
var insertionSortFunc_1 = require("./insertionSortFunc");
var bubbleSortFunc_1 = require("./bubbleSortFunc");
var mergeSortFunc_1 = require("./mergeSortFunc");
var quickSortFunc_1 = require("./quickSortFunc");
var data = common_1.initData(100000);
console.info('start selection sort -> ', new Date());
selectionSortFunc_1.selectionSortFunc(data.slice());
console.info('end selection sort -> ', new Date());
console.info('----------------------------------------------------------------');
console.info('start insertion sort -> ', new Date());
insertionSortFunc_1.insertionSortFunc(data.slice());
console.info('end insertion sort -> ', new Date());
console.info('----------------------------------------------------------------');
console.info('start bubble sort -> ', new Date());
bubbleSortFunc_1.bubbleSortFunc(data.slice());
console.info('end bubble sort -> ', new Date());
console.info('----------------------------------------------------------------');
console.info('start merge sort -> ', new Date());
mergeSortFunc_1.mergeSortFunc(data.slice());
console.info('end merge sort -> ', new Date());
console.info('----------------------------------------------------------------');
console.info('start quick sort -> ', new Date());
quickSortFunc_1.quickSortFunc(data.slice());
console.info('end quick sort -> ', new Date());
